# Butterfly Theme Configuration

# Navigation bar
nav:
  logo:
  display_title: true
  fixed: true
  announcement:

# Menu
menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单:
    music: /music/ || fas fa-music
    movies: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

# Index cover
default_cover: https://images.pexels.com/photos/1292241/pexels-photo-1292241.jpeg

# Footer
footer:
  owner:
    enable: true
    since: 2020
  custom_text:
  copyright: true

# Sidebar
sidebar:
  left:
    sticky: true
  right:
    sticky: true

# aside
aside:
  enable: true
  mobile: true
  position: right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: GitHub
      url: https://github.com/Plocr
  card_announcement:
    enable: true
    content: 欢迎来到Plocrの小窝~
  card_recent_post:
    enable: true
    limit: 5
    sort: date
  card_categories:
    enable: false
  card_tags:
    enable: false
  card_archives:
    enable: false
  card_webinfo:
    enable: false

# Cover of each post
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both

# Post settings
post_meta:
  page:
    date_type: both
    date_format: date
    categories: false
    tags: false
    label: true
  post:
    date_type: both
    date_format: date
    categories: false
    tags: false
    label: true

# Post copyright
post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Highlight theme
highlight_theme: light

# Copy settings
copy:
  enable: true
  copyright:
    enable: false

# Preloader
preloader:
  enable: true
  source: 1

# Avatar
avatar:
  img: /img/TX.gif
  effect: false

# Social icons
social:
  fab fa-github: https://github.com/Plocr || GitHub

# Index page
index:
  tagbar: false
  category: false
  date: true

# Post page
post:
  index_top_img: false
  index_img: false

# Page settings
page:
  music:
    comments: false
  movies:
    comments: false

# Comment
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo/Remark42/Artalk
  use: Valine
  text: true
  # Post button to load comment
  button: true
  lazyload: true
  count: true

# Valine
valine:
  appId: fsuG41IWgzvvtQFFJrqU33Zj-gzGzoHsz
  appKey: qFSD3N3TCjygFIRlY0Ja7DQj
  avatar: monsterid
  serverURLs:
  bg:
  emojiCDN:
  enable: false

# Chat
chat:
  enable: false

# Analysis
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# Dark mode
darkmode:
  enable: true

# Right button
rightside:
  readmode: true
  darkmode: true
  hide_aside: true
  scrollpercent: true

# Ribbon
ribbon:
  enable: false

# Canvas nest
canvas_nest: false

# Background image
background:
  # bg-img: https://xxxx

# Footer background
footer_bg: true

# Social share
social_share:
  enable: true

# Toc
toc:
  post: true
  page: false
  number: true
  expand: false
  open: true

# Lazyload
lazyload:
  enable: false

# Pjax
pjax:
  enable: false

# Powered by
beian:
  enable: false

# Local search
local_search:
  enable: false

# Algolia
algolia:
  enable: false

# Aplayer
aplayer:
  enable: false
